### PR TITLE
Add python wrapper

### PR DESCRIPTION
**Pull request by hawkerpl**
Hi, I created this simple python wrapper for your project, and would like to integrate it.
It exposes just the basic functionality of your code, I might be expanding it a bit soon.

### CODE REVIEW

**Comment by kramer65** [comment]
This is awesome! Exactly what I need!

@DavidEGrayson - When can this be merged?

**Comment by mwmajew** [comment]
You can use my fork until it is merged https://github.com/hawkerpl/minimu9-ahrs

**Comment by hawkerpl** [comment]
Until the merge you can use my fork https://github.com/hawkerpl/minimu9-ahrs

**Comment by kramer65** [comment]
Yeah I already thought of that as well. I'm now first messing with the basic version, testing the calibration and Euler angles. Once that works I'm definitely checking out your fork. Thanks for the code!

**Comment by kramer65** [comment]
Hi @hawkerpl - I tried your fork, but when trying to build it I get the following error:
```
pi@raspberrypi:~/Downloads/minimu9-ahrs-py$ sudo apt-get install python-dev libboost-python-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libboost-python-dev is already the newest version.
python-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~/Downloads/minimu9-ahrs-py$
pi@raspberrypi:~/Downloads/minimu9-ahrs-py$
pi@raspberrypi:~/Downloads/minimu9-ahrs-py$ make
g++  -I. -I/usr/include/eigen3  -Wall --std=gnu++11 -O2 -MD -MP  -c -o python_wrapper.o python_wrapper.cpp
In file included from /usr/include/boost/python/detail/prefix.hpp:13:0,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from python_wrapper.cpp:1:
/usr/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
                       ^
compilation terminated.
<builtin>: recipe for target 'python_wrapper.o' failed
make: *** [python_wrapper.o] Error 1
pi@raspberrypi:~/Downloads/minimu9-ahrs-py$
```
Any idea what could be wrong here?

**Comment by hawkerpl** [comment]
@kramer65  It seems to be some problem with boost, and not the code. Try some solutions from here https://github.com/okfn/piati/issues/65

**Comment by kramer65** [comment]
@hawkerpl - I had a look over the link you gave. They basically advise to `apt install python-dev`, which, as you can see from my previous post, I have already installed. For the rest I don't see anything new in that thread.

Did you try to compile your code on a fresh Raspbian installation?

**Comment by DavidEGrayson** [comment]
I'm not excited about maintain backwards compatibility in the C++ library.  Can you not just run minimu9-ahrs from your Python program? I suppose there might be some reasons to want direct access to it, like if you don't want to deal with pipes and you want control over the timing.  In that case, maybe the minimu9-ahrs could behave as a shared library if that's possible, and provide a few simple, stable C functions.

**Comment by hawkerpl** [comment]
@DavidEGrayson I could alter it in such way that you don't necessarily need to build python wrapper parts, and just have to call the build explicitly. 
Also, in this repository you already use Python and Boost, which are the only components I have used.
@kramer65 I will look into that tomorrow, since I don't have acces to raspberry now

**Comment by cschaal** [comment]
I seem to have exactly the same issues as @kramer65 described earlier. The include paths are not correct and "pyconfig.h" is not found. After adding the proper path, the same problem with boost occurs. Any suggestions?

**Comment by DavidEGrayson** [comment]
Could you try running some commands like this to see if they print useful include flags?

```
pkg-config --cflags python2
pkg-config --cflags python
```

If one of those commands contains `-I/usr/include/python2.7/` then we should add some code in setup.py to run it for us and use the results.  I added such code in setup.py so we can get the eigen3 include directory without hardcoding it.

Please make a pull request or at least post your version of setup.py here if you are able to successfully do this.

**Comment by cschaal** [comment]
The problems occur when trying to compile the code. First when running make, in particular:
> g++  -I. -I/usr/include/eigen3 -Wall -std=gnu++11 -O2 -MD -MP  -c -o python_wrapper.o python_wrapper.cpp

I get
> /usr/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory

With the following modification, it runs fine:
> g++  -I. -I/usr/include/python2.7 -I/usr/include/eigen3 -Wall -std=gnu++11 -O2 -MD -MP  -c -o python_wrapper.o python_wrapper.cpp

However, when it comes to 
> g++   minimu9-ahrs.o python_wrapper.o minimu9.o lis3mdl.o lsm6.o prog_options.o i2c_bus.o lsm303.o l3g.o  -lboost_program_options -o minimu9-ahrs

it fails with (etc.):
> python_wrapper.o: In function `init_module_minimu()':
python_wrapper.cpp:(.text+0xe8): undefined reference to `boost::python::objects::class_base::class_base(char const*, unsigned int, boost::python::type_info const*, char const*)'

I can manually remove python_wrapper.o and compile and use the program just fine. However, I am mostly interested in using the tool in my python code on a Pi3 so I actually need the python_wrapper to work but I don't even get to the setup.py. I hope this clarifies the problem.

To still answer your question:
> pkg-config --cflags python
-I/usr/include/python2.7 -I/usr/include/arm-linux-gnueabihf/python2.7

**Comment by DavidEGrayson** [comment]
Thanks for the info.  I wonder if you really need the Python extension or if you could just run minimu9-ahrs as a command-line program and parse its output.

Normally, users who need the Python extension would follow the instructions in the README and compile the Python extension by running setup.py, but it sounds like you found a different way to get it to work so that's good.

I merged this pull request without really testing it myself or paying attention to the issues people were reporting in this thread; that was probably not warranted.

**Comment by hawkerpl** [comment]
Hi there. 
I'm sorry to say that i ditched this feature, and used straight printout from the thing.
It was because i needed calibration, and the piece of code that does that is really hard to be wrapped for python.
I hope that this at least works for most people with the setup.py i created.

**Comment by hawkerpl** [comment]
The problem is that in makefile https://github.com/DavidEGrayson/minimu9-ahrs/blob/master/Makefile#L1 here it takes all possible .cpp files. We need to exclude python wrapper there, and everything should be fine. (I cannot currently do that, but wanted to help)
Dirty solution for using python wrapper would be to make the project without the python wrapper, and then use setup.py for installing the python wrapper.

**Comment by DavidEGrayson** [comment]
I didn't realize the python wrapper was breaking the main Makefile.  I have removed it, but if someone actually wants to use it and make a good pull request, feel free.

**Comment by cschaal** [comment]
@DavidEGrayson Unfortunately, I cannot get the parsing of the output from the minimu9-ahrs in python to work (in real-time). Do you have a code snippet for that? 

I need to get the current Euler angles every 10ms in order to update the controller for a robot. I can run and terminate the program, read all values in and only take the last but that takes about 800ms. If I leave the program running, I can only read from the beginning of the pipe and will never get to the end (most current value) because it outputs faster than I can read.

**Comment by hawkerpl** [comment]
@cschaal I created this for my own purposes: https://gist.github.com/hawkerpl/5a780badb7775743a6d7c7725e02853c 
It uses multiprocessing.

**Pull request merged**
